name: System Loop

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # jalan tiap 5 jam

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: node index.js
