name: System Monitor

on:
  schedule:
    - cron: "0 */5 * * *" # restart tiap 5 jam otomatis
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # biar auto stop sebelum limit 360 menit (6 jam)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run stealth bot
        run: node index.js
