name: System Monitor

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # jalan tiap 6 jam

jobs:
  stealth-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start bot
      run: npm start
